apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqlite-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/sqlite"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlite-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      initContainers:
      - name: init-db
        image: flask-app
        command:
        - /bin/sh
        - -c
        - |
          flask db init
          flask db migrate -m "Initial migration"
          flask db upgrade
        volumeMounts:
        - name: sqlite-storage
          mountPath: /srv/instance
        - name: migrations
          mountPath: /srv/migrations
      containers:
      - name: flask-app
        image: flask-app
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: sqlite-storage
          mountPath: /srv/instance
        - name: migrations
          mountPath: /srv/migrations
      volumes:
      - name: sqlite-storage
        persistentVolumeClaim:
          claimName: sqlite-pvc
      - name: migrations
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app
spec:
  selector:
    app: flask-app
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP